// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfhmzgqkgxidmsaqpqim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmaG16Z3FrZ3hpZG1zYXFwcWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQyMzQsImV4cCI6MjA3Mzc4MDIzNH0.g9aJQSWieV0dvTfXzKeOAd6dfxOUKXcaMxV_x74NgVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});